const Dinner =[
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'Salmon with Grapefruits',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/rZJJMH4/dinner1.png',
        'price':9.99,
    },
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'Lemony Salmon',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/nQ0cfx1/dinner2.png',
        'price':13.99,
    },
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'Pork Tenderiain',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/kD3BrFv/dinner3.png',
        'price':23.99,
    },
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'Baked Chicken',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/3BBnr3H/dinner4.png',
        'price':15.99,
    },
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'Curlic Butter baked salmon',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/fQRZy1g/dinner5.png',
        'price':7.99,
    },
    {
        'id':'ONION666',
        'category':'Dinner',
        'name':'French fries whit cheese',
        'title':'How we dream about our future',
        'details':'Toothsome, strictly used, refers to edible and pleasant food, or you could even write tasty, appetizing or delicious instead, something really pleasant to the sense of taste. But you will see it very often meaning healthy food, good tasting food that has something more than good taste going for it.',
        'img':'https://i.ibb.co/mCwh4SF/dinner6.png',
        'price':19.99,
    }
]
export default Dinner;